### ISSUE TITLE
Explore Theming Starlight

### ISSUE THREAD

**Issue by dgilleland** [dgilleland/CPSC-1520#8]
Theming Starlight can be as simple as just picking some color/font combinations, or it can be more involved with things like over-riding Starlight components and `.astro` theme files.

This issue is for exploring those themes.

**Comment by dgilleland** [comment]
## Tailwind Color Theme

Based on the [randomizer here](https://starlight.astro.build/guides/css-and-tailwind/#color-theme-editor), I'll call this color theme "**ProgrammerBlue**". It would fit in the `~/src/tailwind.css` file.

```css
/* Dark mode colors. */
:root {
	--sl-color-accent-low: #13243c;
	--sl-color-accent: #2768be;
	--sl-color-accent-high: #b4caea;
	--sl-color-white: #ffffff;
	--sl-color-gray-1: #edeeee;
	--sl-color-gray-2: #c2c2c2;
	--sl-color-gray-3: #8b8b8b;
	--sl-color-gray-4: #585858;
	--sl-color-gray-5: #383838;
	--sl-color-gray-6: #272727;
	--sl-color-black: #181818;
}
/* Light mode colors. */
:root[data-theme='light'] {
	--sl-color-accent-low: #c8d8f0;
	--sl-color-accent: #296ac0;
	--sl-color-accent-high: #173258;
	--sl-color-white: #181818;
	--sl-color-gray-1: #272727;
	--sl-color-gray-2: #383838;
	--sl-color-gray-3: #585858;
	--sl-color-gray-4: #8b8b8b;
	--sl-color-gray-5: #c2c2c2;
	--sl-color-gray-6: #edeeee;
	--sl-color-gray-7: #f6f6f6;
	--sl-color-black: #ffffff;
}
```

**Comment by dgilleland** [comment]
## Tailwind Color Theme - *Late70s*

This is a brown-ish color that might go ok with the orange of the [undraw icons](https://undraw.co/illustrations).

```css
/* Dark mode colors. */
:root {
	--sl-color-accent-low: #322000;
	--sl-color-accent: #8d6000;
	--sl-color-accent-high: #e6c28e;
	--sl-color-white: #ffffff;
	--sl-color-gray-1: #eeeeee;
	--sl-color-gray-2: #c2c2c2;
	--sl-color-gray-3: #8b8b8b;
	--sl-color-gray-4: #585858;
	--sl-color-gray-5: #383838;
	--sl-color-gray-6: #272727;
	--sl-color-black: #181818;
}
/* Light mode colors. */
:root[data-theme='light'] {
	--sl-color-accent-low: #edd2ab;
	--sl-color-accent: #8f6200;
	--sl-color-accent-high: #452d00;
	--sl-color-white: #181818;
	--sl-color-gray-1: #272727;
	--sl-color-gray-2: #383838;
	--sl-color-gray-3: #585858;
	--sl-color-gray-4: #8b8b8b;
	--sl-color-gray-5: #c2c2c2;
	--sl-color-gray-6: #eeeeee;
	--sl-color-gray-7: #f6f6f6;
	--sl-color-black: #ffffff;
}
```
